baseurl = "http://www.example.com"
title = "Sean Mata"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
author = "Sean Mata"
description = "A personal website for Sean"
keywords = "blog,developer,personal"
info = ["Former Princeton University Exchange Student","4th Year Engineer at the University of Oxford","RAEng Engineering Leaders Scholar","Formula One Scholar"]
avatarURL = "images/avatar2.jpg"
#gravatar = "john.doe@example.com"
#footerContent = ""
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2021
# Git Commit in Footer, uncomment the line below to enable it

# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false


#[taxonomies]
#  category = "categories"
#  series = "series"
#  tag = "tags"
#  author = "authors"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"


[[menu.main]]
  name = "Contact me"
  weight = 6
  url = "contact/"

[markup]
[markup.tableOfContents]
  startLevel = 3
  endLevel = 3